/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanaceTokenSol from "./GovernanaceToken.sol";
export type { governanaceTokenSol };
import type * as governanceStandard from "./governance_standard";
export type { governanceStandard };
export type { Box } from "./Box";
